/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package autoserver;


import utility.Tools;

import java.io.*; 
import java.net.*;





public class GraficaServer extends javax.swing.JFrame{

        private boolean cont = false;

        
        
        Thread aggiornaParametriGui = new Thread (new AggiornaParametriGui());
        

    
        ServerSocket serverSocket;

        
        Socket socket;

        ObjectInputStream inOBJ;
        ObjectOutputStream outOBJ;
        




    public GraficaServer() {
        initComponents();
        this.setSize (lblCruscotto.getWidth(), lblCruscotto.getHeight()+150);
        this.setLocation(10, 10);                                   // (x,y)
        setTitle("Server (Automobile)");
        
        reset (); 

        aggiornaParametriGui.start ();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgAllarme = new javax.swing.JLabel();
        imgBlocco = new javax.swing.JLabel();
        imgRiserva = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        lblMotore = new javax.swing.JLabel();
        lblMotoreV = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        lblBatteria = new javax.swing.JLabel();
        lblOlio = new javax.swing.JLabel();
        lblGomme = new javax.swing.JLabel();
        lblKm = new javax.swing.JLabel();
        lblCarburante = new javax.swing.JLabel();
        lblKmV = new javax.swing.JLabel();
        prgCarburante = new javax.swing.JProgressBar();
        prgGomme = new javax.swing.JProgressBar();
        prgOlio = new javax.swing.JProgressBar();
        prgBatteria = new javax.swing.JProgressBar();
        lblNetwork = new javax.swing.JLabel();
        lblNetworkV = new javax.swing.JLabel();
        lblLongitudineV = new javax.swing.JLabel();
        lblLongitudine = new javax.swing.JLabel();
        lblLatitudineV = new javax.swing.JLabel();
        lblLatitudine = new javax.swing.JLabel();
        lblCruscotto = new javax.swing.JLabel();
        txtDbIp = new javax.swing.JTextField();
        txtDbUsername = new javax.swing.JTextField();
        txtDbPassword = new javax.swing.JPasswordField();
        lblDbUsername = new javax.swing.JLabel();
        lblDbPassword = new javax.swing.JLabel();
        lblDbIp = new javax.swing.JLabel();
        btnModifica = new javax.swing.JButton();
        lblNClientV = new javax.swing.JLabel();
        lblNClient = new javax.swing.JLabel();
        btnArresta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        imgAllarme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoserver/Allarme.png"))); // NOI18N
        imgAllarme.setText("imgAllarme");
        getContentPane().add(imgAllarme);
        imgAllarme.setBounds(150, 130, 45, 50);

        imgBlocco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoserver/Blocco.png"))); // NOI18N
        imgBlocco.setText("imgBlocco");
        imgBlocco.setBounds(new java.awt.Rectangle(120, 290, 50, 43));
        getContentPane().add(imgBlocco);
        imgBlocco.setBounds(120, 290, 50, 43);

        imgRiserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoserver/Riserva.png"))); // NOI18N
        getContentPane().add(imgRiserva);
        imgRiserva.setBounds(180, 290, 50, 50);

        console.setEditable(false);
        console.setColumns(1);
        console.setFont(new java.awt.Font("Lucida Grande", 0, 9)); // NOI18N
        console.setRows(1);
        console.setDragEnabled(false);
        console.setFocusable(false);
        jScrollPane1.setViewportView(console);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 390, 250, 90);

        lblMotore.setText("Motore:");
        getContentPane().add(lblMotore);
        lblMotore.setBounds(570, 320, 48, 16);

        lblMotoreV.setText("No Data");
        lblMotoreV.setEnabled(false);
        lblMotoreV.setFocusable(false);
        getContentPane().add(lblMotoreV);
        lblMotoreV.setBounds(650, 320, 51, 16);

        display.setEditable(false);
        display.setColumns(1);
        display.setFont(new java.awt.Font("Lucida Grande", 0, 9)); // NOI18N
        display.setRows(1);
        display.setDragEnabled(false);
        display.setFocusable(false);
        jScrollPane2.setViewportView(display);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(350, 160, 110, 150);

        lblBatteria.setText("Batteria:");
        getContentPane().add(lblBatteria);
        lblBatteria.setBounds(320, 100, 51, 16);

        lblOlio.setText("Olio:");
        getContentPane().add(lblOlio);
        lblOlio.setBounds(320, 80, 30, 16);

        lblGomme.setText("Gomme:");
        getContentPane().add(lblGomme);
        lblGomme.setBounds(320, 60, 52, 16);

        lblKm.setText("Km Totali:");
        getContentPane().add(lblKm);
        lblKm.setBounds(570, 300, 64, 16);

        lblCarburante.setText("Carburante:");
        getContentPane().add(lblCarburante);
        lblCarburante.setBounds(320, 40, 73, 16);

        lblKmV.setText("No Data");
        lblKmV.setEnabled(false);
        lblKmV.setFocusable(false);
        getContentPane().add(lblKmV);
        lblKmV.setBounds(650, 300, 51, 16);
        getContentPane().add(prgCarburante);
        prgCarburante.setBounds(410, 40, 80, 20);
        getContentPane().add(prgGomme);
        prgGomme.setBounds(410, 60, 80, 20);
        getContentPane().add(prgOlio);
        prgOlio.setBounds(410, 80, 80, 20);
        getContentPane().add(prgBatteria);
        prgBatteria.setBounds(410, 100, 80, 20);

        lblNetwork.setText("Network:");
        getContentPane().add(lblNetwork);
        lblNetwork.setBounds(630, 430, 57, 16);

        lblNetworkV.setText("Offline");
        getContentPane().add(lblNetworkV);
        lblNetworkV.setBounds(710, 430, 43, 16);

        lblLongitudineV.setText("No Data");
        lblLongitudineV.setEnabled(false);
        lblLongitudineV.setFocusable(false);
        getContentPane().add(lblLongitudineV);
        lblLongitudineV.setBounds(120, 510, 160, 16);

        lblLongitudine.setText("Longitudine:");
        getContentPane().add(lblLongitudine);
        lblLongitudine.setBounds(10, 510, 79, 16);

        lblLatitudineV.setText("No Data");
        lblLatitudineV.setEnabled(false);
        lblLatitudineV.setFocusable(false);
        getContentPane().add(lblLatitudineV);
        lblLatitudineV.setBounds(120, 490, 160, 16);

        lblLatitudine.setText("Latitudine:");
        getContentPane().add(lblLatitudine);
        lblLatitudine.setBounds(10, 490, 67, 16);

        lblCruscotto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autoserver/Cruscotto.png"))); // NOI18N
        lblCruscotto.setBounds(new java.awt.Rectangle(0, 0, 807, 495));
        getContentPane().add(lblCruscotto);
        lblCruscotto.setBounds(0, 0, 807, 495);

        txtDbIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDbIpActionPerformed(evt);
            }
        });
        getContentPane().add(txtDbIp);
        txtDbIp.setBounds(660, 490, 140, 28);
        getContentPane().add(txtDbUsername);
        txtDbUsername.setBounds(660, 520, 140, 28);
        getContentPane().add(txtDbPassword);
        txtDbPassword.setBounds(660, 550, 140, 28);

        lblDbUsername.setText("Username");
        getContentPane().add(lblDbUsername);
        lblDbUsername.setBounds(550, 530, 110, 16);

        lblDbPassword.setText("Password");
        getContentPane().add(lblDbPassword);
        lblDbPassword.setBounds(550, 560, 110, 16);

        lblDbIp.setText("Indirizzo");
        getContentPane().add(lblDbIp);
        lblDbIp.setBounds(550, 500, 110, 16);

        btnModifica.setText("Abilita Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifica);
        btnModifica.setBounds(547, 590, 260, 29);

        lblNClientV.setText("No Data");
        lblNClientV.setEnabled(false);
        lblNClientV.setFocusable(false);
        getContentPane().add(lblNClientV);
        lblNClientV.setBounds(120, 560, 60, 16);

        lblNClient.setText("Client connessi:");
        getContentPane().add(lblNClient);
        lblNClient.setBounds(10, 560, 101, 16);

        btnArresta.setText("Arresta Server");
        btnArresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnArresta);
        btnArresta.setBounds(0, 590, 230, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDbIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDbIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDbIpActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        if (cont == false){
            lblDbIp.setEnabled (true);
            lblDbUsername.setEnabled (true);
            lblDbPassword.setEnabled (true);

            txtDbIp.setEnabled (true);
            txtDbUsername.setEnabled (true);
            txtDbPassword.setEnabled (true);

            btnModifica.setText ("OK");
            
            cont = true;
        }
        
        else {
            lblDbIp.setEnabled (false);
            lblDbUsername.setEnabled (false);
            lblDbPassword.setEnabled (false);
        
            txtDbIp.setEnabled (false);
            txtDbUsername.setEnabled (false);
            txtDbPassword.setEnabled (false);
            
            btnModifica.setText ("Abilita Modifica");
            
            cont = false;
        }

    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnArrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrestaActionPerformed
        try {
            socket.close();
        } catch (Exception e){}
        System.exit(0);
        
    }//GEN-LAST:event_btnArrestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraficaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraficaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraficaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraficaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraficaServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArresta;
    private javax.swing.JButton btnModifica;
    private javax.swing.JTextArea console;
    private javax.swing.JTextArea display;
    private javax.swing.JLabel imgAllarme;
    private javax.swing.JLabel imgBlocco;
    private javax.swing.JLabel imgRiserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBatteria;
    private javax.swing.JLabel lblCarburante;
    private javax.swing.JLabel lblCruscotto;
    private javax.swing.JLabel lblDbIp;
    private javax.swing.JLabel lblDbPassword;
    private javax.swing.JLabel lblDbUsername;
    private javax.swing.JLabel lblGomme;
    private javax.swing.JLabel lblKm;
    private javax.swing.JLabel lblKmV;
    private javax.swing.JLabel lblLatitudine;
    private javax.swing.JLabel lblLatitudineV;
    private javax.swing.JLabel lblLongitudine;
    private javax.swing.JLabel lblLongitudineV;
    private javax.swing.JLabel lblMotore;
    private javax.swing.JLabel lblMotoreV;
    private javax.swing.JLabel lblNClient;
    private javax.swing.JLabel lblNClientV;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblNetworkV;
    private javax.swing.JLabel lblOlio;
    private javax.swing.JProgressBar prgBatteria;
    private javax.swing.JProgressBar prgCarburante;
    private javax.swing.JProgressBar prgGomme;
    private javax.swing.JProgressBar prgOlio;
    private javax.swing.JTextField txtDbIp;
    private javax.swing.JPasswordField txtDbPassword;
    private javax.swing.JTextField txtDbUsername;
    // End of variables declaration//GEN-END:variables

  
    
    
    public String getIp (){
        return txtDbIp.getText();
    }
    
    public String getUsername (){
        return txtDbUsername.getText();
    }
    
    public String getPassword (){
        return new String(txtDbPassword.getPassword());
    }

    public void setConsole (String testo){
        Tools.scrivi (console,testo);
    }
    
    public void setDisplay (String testo){
        Tools.scrivi (display,testo);
    }
    
    
    private void reset (){
        console.setText ("");
        console.append ("\n\n\n\n\n\n-Sistema Inizializzato");
        display.append ("\n\n\n\n\n\n\n\n\n\n\n\n");
        Tools.colora (lblNetworkV,255,0,0);
        
        
        Tools.colora (lblCarburante,255,255,255);
        Tools.colora (lblGomme,255,255,255);
        Tools.colora (lblOlio,255,255,255);
        Tools.colora (lblBatteria,255,255,255);
        Tools.colora (lblNetwork,255,255,255);
        Tools.colora (lblKm,255,255,255);
        Tools.colora (lblKmV,255,255,255);
        Tools.colora (lblMotore,255,255,255);
        Tools.colora (lblMotoreV,255,255,255);
        
        imgAllarme.setVisible (false);
        imgBlocco.setVisible (false);
        imgRiserva.setVisible (false);
        
        txtDbIp.setText ("localhost");
        txtDbUsername.setText ("root");
        txtDbPassword.setText ("");
        
        lblDbIp.setEnabled (false);
        lblDbUsername.setEnabled (false);
        lblDbPassword.setEnabled (false);
        
        txtDbIp.setEnabled (false);
        txtDbUsername.setEnabled (false);
        txtDbPassword.setEnabled (false);
 
        cont = false;

        
    }

    

    
    

    
    
    public class AggiornaParametriGui implements Runnable {
        @Override
        public void run()
        {
            while (true){
               
                if (AutoServer.getAllarme() == true)        { imgAllarme.setVisible (true);}
                
                    else                                        { imgAllarme.setVisible (false);}
                
                
                if (AutoServer.getBlocco() == true)         { imgBlocco.setVisible (true);}
                    else                                    { imgBlocco.setVisible (false);}
                
                
                if (AutoServer.getAccensione() == true)     
                        { lblMotoreV.setText ("Acceso"); Tools.colora (lblMotoreV,0,255,0);}
                    else                    
                        { lblMotoreV.setText ("Spento"); Tools.colora (lblMotoreV,255,0,0);}
                
                
                
                    
                
                lblKmV.setText (Integer.toString(AutoServer.getKmTotali()));
                lblLatitudineV.setText (AutoServer.getLatitudine());
                lblLongitudineV.setText (AutoServer.getLongitudine());

                
                prgCarburante.setValue(AutoServer.getCarburante());
                prgGomme.setValue(AutoServer.getGomme());
                prgOlio.setValue(AutoServer.getOlio());
                prgBatteria.setValue(AutoServer.getBatteria());
                
                if (AutoServer.getCarburante() < 30 )       { imgRiserva.setVisible (true);}
                    else                                    { imgRiserva.setVisible (false);}

                
                //System.out.println ("Acc: "+Boolean.toString(accensione)+" // EV: "+Boolean.toString(blocco)+" // AL: "+Boolean.toString(allarme));
                
                lblNClientV.setText(Integer.toString(AutoServer.getNumeroClient ()));
                
                if (AutoServer.getNumeroClient () > 0 ){
                    Tools.colora (lblNetworkV,0,255,0);
                    lblNetworkV.setText ("Online");
                }
                
                else {
                    
                    Tools.colora (lblNetworkV,255,0,0);
                    lblNetworkV.setText ("Offline");
                
                }
                
                try {
                    Thread.sleep (1000);
                } catch (Exception e) {}
            }
        
        }
        
    }
    
    
}





