/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package autocentralina;

import utility.Pacchetto;
import utility.Dati;
import utility.Tools;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;



/**
 *
 * @author salvatorenitopi
 */
public class Centralina extends javax.swing.JFrame {

    
    
    Socket socket;

    ObjectInputStream inOBJ;
    ObjectOutputStream outOBJ;


   
    public Centralina() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize (800, 252);
        this.setLocation(10, dim.height-262);                                   // (x,y)
        
        setTitle("Pannello di controllo (Centralina)");
        Tools.colora (lblNetworkV,255,0,0);
        
        console.setText ("");
        console.setText ("\n\n\n\n\n\n\n-Sistema Inizializzato");
        
        bntParametri.setEnabled (false);
           
        
        
        reset ();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsole = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        lblCarburante = new javax.swing.JLabel();
        lblKm = new javax.swing.JLabel();
        lblGomme = new javax.swing.JLabel();
        lblOlio = new javax.swing.JLabel();
        lblBatteria = new javax.swing.JLabel();
        txtCarburante = new javax.swing.JTextField();
        txtKm = new javax.swing.JTextField();
        txtGomme = new javax.swing.JTextField();
        txtOlio = new javax.swing.JTextField();
        txtBatteria = new javax.swing.JTextField();
        bntParametri = new javax.swing.JButton();
        lblAzioni1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        bntEsci = new javax.swing.JButton();
        chkAccensione = new java.awt.Checkbox();
        txtLongitudine = new javax.swing.JTextField();
        txtLatitudine = new javax.swing.JTextField();
        lblLongitudine = new javax.swing.JLabel();
        lblLatitudine = new javax.swing.JLabel();
        chkBlocco = new java.awt.Checkbox();
        lblAzioni = new javax.swing.JLabel();
        chkAllarme = new java.awt.Checkbox();
        btnConnetti = new javax.swing.JButton();
        lblNetworkV = new javax.swing.JLabel();
        lblNetwork = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        txtPorta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        lblConsole.setText("Console");

        console.setEditable(false);
        console.setColumns(20);
        console.setRows(5);
        console.setDragEnabled(false);
        console.setFocusable(false);
        jScrollPane1.setViewportView(console);

        lblCarburante.setText("Carburante:");

        lblKm.setText("Km Totali:");

        lblGomme.setText("Gomme:");

        lblOlio.setText("Olio:");

        lblBatteria.setText("Batteria:");

        txtCarburante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarburanteActionPerformed(evt);
            }
        });

        txtKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmActionPerformed(evt);
            }
        });

        txtGomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGommeActionPerformed(evt);
            }
        });

        txtOlio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOlioActionPerformed(evt);
            }
        });

        txtBatteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatteriaActionPerformed(evt);
            }
        });

        bntParametri.setText("Invia");
        bntParametri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntParametriActionPerformed(evt);
            }
        });

        lblAzioni1.setText("Parametri");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        bntEsci.setText("Esci");
        bntEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEsciActionPerformed(evt);
            }
        });

        chkAccensione.setLabel("Accensione");

        txtLongitudine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudineActionPerformed(evt);
            }
        });

        txtLatitudine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatitudineActionPerformed(evt);
            }
        });

        lblLongitudine.setText("Longitudine:");

        lblLatitudine.setText("Latitudine:");

        chkBlocco.setLabel("Blocco");

        lblAzioni.setText("Azioni");

        chkAllarme.setLabel("Allarme");

        btnConnetti.setText("Connetti");
        btnConnetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnettiActionPerformed(evt);
            }
        });

        lblNetworkV.setText("Offline");

        lblNetwork.setText("Network:");

        txtIp.setText("127.0.0.1");

        txtPorta.setText("11111");
        txtPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAzioni)
                    .addComponent(chkAccensione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkBlocco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAllarme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntEsci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAzioni1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblKm)
                                        .addGap(21, 21, 21)
                                        .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCarburante)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtCarburante, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblGomme)
                                        .addGap(33, 33, 33)
                                        .addComponent(txtGomme, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblOlio)
                                            .addComponent(lblLatitudine)
                                            .addComponent(lblBatteria))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblLongitudine)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOlio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBatteria, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLatitudine, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLongitudine, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 31, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntParametri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConnetti)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsole)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtIp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblNetwork)
                        .addGap(33, 33, 33)
                        .addComponent(lblNetworkV)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAzioni)
                    .addComponent(lblAzioni1))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkAccensione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(chkBlocco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkAllarme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblKm)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCarburante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblCarburante)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtGomme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(lblGomme)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNetworkV)
                                .addComponent(lblNetwork)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntEsci)
                            .addComponent(bntParametri)
                            .addComponent(btnConnetti)
                            .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBatteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBatteria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOlio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOlio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLatitudine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLatitudine))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLongitudine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLongitudine))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblConsole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCarburanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarburanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarburanteActionPerformed

    private void txtKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmActionPerformed

    private void txtGommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGommeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGommeActionPerformed

    private void txtOlioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOlioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOlioActionPerformed

    private void txtBatteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatteriaActionPerformed

    private void bntParametriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntParametriActionPerformed
        oggettoClient (outOBJ);

    }//GEN-LAST:event_bntParametriActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void bntEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEsciActionPerformed
        messaggioDisconnetti ();
        System.exit(0);
    }//GEN-LAST:event_bntEsciActionPerformed

    private void txtLongitudineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitudineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitudineActionPerformed

    private void txtLatitudineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLatitudineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLatitudineActionPerformed

    private void btnConnettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnettiActionPerformed
        connetti ();
    }//GEN-LAST:event_btnConnettiActionPerformed

    private void txtPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Centralina().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEsci;
    private javax.swing.JButton bntParametri;
    private javax.swing.JButton btnConnetti;
    private javax.swing.JButton btnReset;
    private java.awt.Checkbox chkAccensione;
    private java.awt.Checkbox chkAllarme;
    private java.awt.Checkbox chkBlocco;
    private javax.swing.JTextArea console;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAzioni;
    private javax.swing.JLabel lblAzioni1;
    private javax.swing.JLabel lblBatteria;
    private javax.swing.JLabel lblCarburante;
    private javax.swing.JLabel lblConsole;
    private javax.swing.JLabel lblGomme;
    private javax.swing.JLabel lblKm;
    private javax.swing.JLabel lblLatitudine;
    private javax.swing.JLabel lblLongitudine;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblNetworkV;
    private javax.swing.JLabel lblOlio;
    private javax.swing.JTextField txtBatteria;
    private javax.swing.JTextField txtCarburante;
    private javax.swing.JTextField txtGomme;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextField txtLatitudine;
    private javax.swing.JTextField txtLongitudine;
    private javax.swing.JTextField txtOlio;
    private javax.swing.JTextField txtPorta;
    // End of variables declaration//GEN-END:variables

    private void reset (){
        
        chkAccensione.setState(false);
        chkAllarme.setState(false);
        chkBlocco.setState(false);
        
        txtKm.setText("1000");
        txtCarburante.setText("25");
        txtGomme.setText("60");
        txtOlio.setText("70");
        txtBatteria.setText("80");
        
        txtLatitudine.setText("38.259908");
        txtLongitudine.setText("15.594926");

    }
    
    private void connetti (){
        try{
            
            Tools.scrivi (console,"Tentativo di accesso sul server: "+txtIp.getText()+":"+txtPorta.getText()+"...");
            
            socket=new Socket(txtIp.getText(),Integer.parseInt(txtPorta.getText()));
            
            Tools.colora (lblNetworkV,0,255,0);
            lblNetworkV.setText ("Online");
            Tools.scrivi (console,"Connesso");
            btnConnetti.setEnabled (false);
            bntParametri.setEnabled (true);
            
            
            outOBJ=new ObjectOutputStream(socket.getOutputStream());
            //inOBJ=new ObjectInputStream(socket.getInputStream());
            
            messaggioClient ("Centralina", outOBJ, 9);                          // Identificazione
            
            
            } catch(Exception e){
            Tools.scrivi (console,"ERRORE TENTATIVO CONNESSIONE.");
                    System.out.println (e);
            }
    }
    
    
    private void messaggioClient (String mess, ObjectOutputStream out, int tipo) {

        try
        {   
            Pacchetto invia = new Pacchetto ();
            
            invia.setTipo(tipo);
            invia.setOggetto (mess);
            
            
            out.writeObject(invia);
            out.flush();
            Tools.scrivi (console,"Messaggio Inviato ("+mess+")");
         } catch(Exception e){
             Tools.scrivi (console,"ERRORE INVIO MESSAGGIO.");
             System.out.println (e);
         }
        
    }
    
    
    
    private void messaggioDisconnetti () {

        try
        {   
            
            Pacchetto invia = new Pacchetto ();
            
            invia.setTipo(0);

            outOBJ.writeObject(invia);
            outOBJ.flush();
            Tools.scrivi (console,"Messaggio Disc. Inviato");
         } catch(Exception e){
             Tools.scrivi (console,"ERRORE MESS. DISCONNESSIONE...");
             System.out.println (e);
         }
        
    }
    
    private void oggettoClient (ObjectOutputStream out) {

        if (Tools.stringaNumero(txtKm.getText()) == true &&
            Tools.stringaNumero(txtCarburante.getText()) == true &&
            Tools.stringaNumero(txtGomme.getText()) == true &&
            Tools.stringaNumero(txtOlio.getText()) == true &&
            Tools.stringaNumero(txtBatteria.getText()) == true){
            
            Tools.scrivi (console, "Parametri validi.");
        
            try
            {


                Dati dati = new Dati ();

                    dati.setAccensione(chkAccensione.getState());
                    dati.setAllarme(chkAllarme.getState());
                    dati.setBlocco(chkBlocco.getState());

                    dati.setKmTotali (Integer.parseInt(txtKm.getText()));
                    dati.setCarburante (Integer.parseInt(txtCarburante.getText()));
                    dati.setGomme(Integer.parseInt(txtGomme.getText()));
                    dati.setOlio(Integer.parseInt(txtOlio.getText()));
                    dati.setBatteria(Integer.parseInt(txtBatteria.getText()));

                    dati.setLatitudine(txtLatitudine.getText());
                    dati.setLongitudine(txtLongitudine.getText());



                Pacchetto invia = new Pacchetto ();

                invia.setTipo(2);
                invia.setOggetto (dati);


                out.writeObject(invia);
                out.flush();
                    
                chkAccensione.setState(false);
                chkAllarme.setState(false);
                chkBlocco.setState(false);
            
                    Tools.scrivi (console,"Parametri Aggiornati.");

            } catch(Exception e){
                 System.out.println (e);
            }
        
        }
        
        else {
            
            Tools.scrivi (console, "PARAMETRI NON VALIDI.");
            
        }
        
    }
    
}
