package autoclient;

import utility.Tools;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author salvatorenitopi
 */
public class Cronologia extends javax.swing.JFrame {

    
    public Cronologia() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize (500,415);
        this.setLocation(dim.width - 490, 10);
        this.setTitle ("Cronologia");

        Tools.colora (lblBlocco, 255,0,0);
        Tools.colora (lblAllarme, 255,0,0);
        
        
        sqlQuery ();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblMotore = new javax.swing.JLabel();
        lblBlocco = new javax.swing.JLabel();
        lblAllarme = new javax.swing.JLabel();
        lblData1 = new javax.swing.JLabel();
        lblLongitudine1 = new javax.swing.JLabel();
        lblLatitudine1 = new javax.swing.JLabel();
        lblLongitudine2 = new javax.swing.JLabel();
        lblLatitudine2 = new javax.swing.JLabel();
        lblData2 = new javax.swing.JLabel();
        lblLongitudine3 = new javax.swing.JLabel();
        lblLatitudine3 = new javax.swing.JLabel();
        lblData3 = new javax.swing.JLabel();
        lblLongitudineV1 = new javax.swing.JLabel();
        lblLatitudineV1 = new javax.swing.JLabel();
        lblDataV1 = new javax.swing.JLabel();
        lblDataV2 = new javax.swing.JLabel();
        lblLongitudineV2 = new javax.swing.JLabel();
        lblLatitudineV2 = new javax.swing.JLabel();
        lblLongitudineV3 = new javax.swing.JLabel();
        lblLatitudineV3 = new javax.swing.JLabel();
        lblDataV3 = new javax.swing.JLabel();
        lblCronologia = new javax.swing.JLabel();
        lblPosizione = new javax.swing.JLabel();
        btnAggiorna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Esci");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblMotore.setText("Ultimo avvio motore:");

        lblBlocco.setText("Ultimo blocco:");

        lblAllarme.setText("Ultimo allarme:");

        lblData1.setText("Data");

        lblLongitudine1.setText("Longitudine");

        lblLatitudine1.setText("Latitudine");

        lblLongitudine2.setText("Longitudine");

        lblLatitudine2.setText("Latitudine");

        lblData2.setText("Data");

        lblLongitudine3.setText("Longitudine");

        lblLatitudine3.setText("Latitudine");

        lblData3.setText("Data");

        lblLongitudineV1.setText("Longitudine");

        lblLatitudineV1.setText("Latitudine");

        lblDataV1.setText("Data");

        lblDataV2.setText("Data");

        lblLongitudineV2.setText("Longitudine");

        lblLatitudineV2.setText("Latitudine");

        lblLongitudineV3.setText("Longitudine");

        lblLatitudineV3.setText("Latitudine");

        lblDataV3.setText("Data");

        lblCronologia.setText("Cronologia");

        lblPosizione.setText("Ultima posizione nota");

        btnAggiorna.setText("Aggiorna");
        btnAggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiornaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMotore)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBlocco)
                                    .addComponent(lblAllarme)
                                    .addComponent(lblDataV3)
                                    .addComponent(lblDataV2)
                                    .addComponent(lblDataV1)
                                    .addComponent(lblData2)
                                    .addComponent(lblData3)
                                    .addComponent(lblData1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLongitudineV3)
                                    .addComponent(lblLongitudineV2)
                                    .addComponent(lblLongitudineV1)
                                    .addComponent(lblLongitudine2)
                                    .addComponent(lblLongitudine3)
                                    .addComponent(lblLongitudine1))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLatitudineV3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLatitudineV2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLatitudineV1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLatitudine2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLatitudine3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLatitudine1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCronologia)
                            .addComponent(lblPosizione))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAggiorna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCronologia)
                .addGap(18, 18, 18)
                .addComponent(lblPosizione)
                .addGap(18, 18, 18)
                .addComponent(lblMotore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblData1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDataV1)
                            .addGap(40, 40, 40)
                            .addComponent(lblBlocco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblData2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDataV2)
                            .addGap(43, 43, 43)
                            .addComponent(lblAllarme)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblData3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDataV3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLongitudine1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblLongitudineV1)
                            .addGap(62, 62, 62)
                            .addComponent(lblLongitudine2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblLongitudineV2)
                            .addGap(65, 65, 65)
                            .addComponent(lblLongitudine3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblLongitudineV3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLatitudine1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLatitudineV1)
                        .addGap(62, 62, 62)
                        .addComponent(lblLatitudine2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLatitudineV2)
                        .addGap(65, 65, 65)
                        .addComponent(lblLatitudine3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLatitudineV3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnAggiorna))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible (false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiornaActionPerformed
        sqlQuery ();
    }//GEN-LAST:event_btnAggiornaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cronologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cronologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cronologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cronologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cronologia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiorna;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAllarme;
    private javax.swing.JLabel lblBlocco;
    private javax.swing.JLabel lblCronologia;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblData2;
    private javax.swing.JLabel lblData3;
    private javax.swing.JLabel lblDataV1;
    private javax.swing.JLabel lblDataV2;
    private javax.swing.JLabel lblDataV3;
    private javax.swing.JLabel lblLatitudine1;
    private javax.swing.JLabel lblLatitudine2;
    private javax.swing.JLabel lblLatitudine3;
    private javax.swing.JLabel lblLatitudineV1;
    private javax.swing.JLabel lblLatitudineV2;
    private javax.swing.JLabel lblLatitudineV3;
    private javax.swing.JLabel lblLongitudine1;
    private javax.swing.JLabel lblLongitudine2;
    private javax.swing.JLabel lblLongitudine3;
    private javax.swing.JLabel lblLongitudineV1;
    private javax.swing.JLabel lblLongitudineV2;
    private javax.swing.JLabel lblLongitudineV3;
    private javax.swing.JLabel lblMotore;
    private javax.swing.JLabel lblPosizione;
    // End of variables declaration//GEN-END:variables

    private void sqlQuery (){
        
            Preferenze.leggiXML();
        try {
            
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://"+Preferenze.getIndirizzoSql()+"/AutoMonitoring?" + 
                        "user="+Preferenze.getUsernameSql()+"&"+String.valueOf(Preferenze.getPasswordSql())+"=");
                Statement stmt;
                ResultSet rs;

                stmt = conn.createStatement();

                rs = stmt.executeQuery("SELECT * "
                        + "FROM Cronologia "
                        + "WHERE data = (SELECT MAX(data) FROM Cronologia)");

                while(rs.next())
                {

                    lblCronologia.setText ("Cronologia posizioni automobile "
                            + "(Aggiornata al: "+rs.getString("data")+").");
   
                    lblPosizione.setText ("Ultima posizione nota: "+rs.getString("latitudine")+"  /  "+rs.getString("longitudine"));

                }

                //////////////////////////////////////////////////////////////////////////////////////////////////////
                
                rs = stmt.executeQuery("SELECT * "
                        + "FROM Cronologia "
                        + "WHERE data = (SELECT MAX(data) FROM Cronologia AS C WHERE C.avvioMotore = 1)");


                while(rs.next())
                {

                    lblDataV1.setText(rs.getString("data"));
                    lblLongitudineV1.setText(rs.getString("latitudine"));
                    lblLatitudineV1.setText(rs.getString("longitudine"));

                }

                //////////////////////////////////////////////////////////////////////////////////////////////////////

                rs = stmt.executeQuery("SELECT * "
                        + "FROM Cronologia "
                        + "WHERE data = (SELECT MAX(data) FROM Cronologia AS C WHERE C.blocco = 1)");


                while(rs.next())
                {

                    lblDataV2.setText(rs.getString("data"));
                    lblLongitudineV2.setText(rs.getString("latitudine"));
                    lblLatitudineV2.setText(rs.getString("longitudine"));

                }

                //////////////////////////////////////////////////////////////////////////////////////////////////////
   
                rs = stmt.executeQuery("SELECT * "
                        + "FROM Cronologia "
                        + "WHERE data = (SELECT MAX(data) "
                        + "FROM Cronologia AS C WHERE C.allarme = 1)");


                while(rs.next())
                {

                    lblDataV3.setText(rs.getString("data"));
                    lblLongitudineV3.setText(rs.getString("latitudine"));
                    lblLatitudineV3.setText(rs.getString("longitudine"));

                }
   
                stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
                //Tools.scrivi (console,"Errore: "+e);
            }
        
    }

    
}
